#############################################################################
# Makefile for building: insight-vmi
# Generated by qmake (2.01a) (Qt 4.7.3) on: Do. Sep 8 01:25:02 2011
# Project:  insight-vmi.pro
# Template: subdirs
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile insight-vmi.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-libantlr3c \
		sub-libcparser \
		sub-libinsight \
		sub-insightd \
		sub-insight

libantlr3c/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libantlr3c/ || $(MKDIR) libantlr3c/ 
	cd libantlr3c/ && $(QMAKE) /home/chrschn/workspace/insight-vmi/libantlr3c/libantlr3c.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-libantlr3c-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libantlr3c/ || $(MKDIR) libantlr3c/ 
	cd libantlr3c/ && $(QMAKE) /home/chrschn/workspace/insight-vmi/libantlr3c/libantlr3c.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-libantlr3c: libantlr3c/$(MAKEFILE) FORCE
	cd libantlr3c/ && $(MAKE) -f $(MAKEFILE)
sub-libantlr3c-make_default-ordered: libantlr3c/$(MAKEFILE) FORCE
	cd libantlr3c/ && $(MAKE) -f $(MAKEFILE) 
sub-libantlr3c-make_default: libantlr3c/$(MAKEFILE) FORCE
	cd libantlr3c/ && $(MAKE) -f $(MAKEFILE) 
sub-libantlr3c-make_first-ordered: libantlr3c/$(MAKEFILE) FORCE
	cd libantlr3c/ && $(MAKE) -f $(MAKEFILE) first
sub-libantlr3c-make_first: libantlr3c/$(MAKEFILE) FORCE
	cd libantlr3c/ && $(MAKE) -f $(MAKEFILE) first
sub-libantlr3c-all-ordered: libantlr3c/$(MAKEFILE) FORCE
	cd libantlr3c/ && $(MAKE) -f $(MAKEFILE) all
sub-libantlr3c-all: libantlr3c/$(MAKEFILE) FORCE
	cd libantlr3c/ && $(MAKE) -f $(MAKEFILE) all
sub-libantlr3c-clean-ordered: libantlr3c/$(MAKEFILE) FORCE
	cd libantlr3c/ && $(MAKE) -f $(MAKEFILE) clean
sub-libantlr3c-clean: libantlr3c/$(MAKEFILE) FORCE
	cd libantlr3c/ && $(MAKE) -f $(MAKEFILE) clean
sub-libantlr3c-distclean-ordered: libantlr3c/$(MAKEFILE) FORCE
	cd libantlr3c/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libantlr3c-distclean: libantlr3c/$(MAKEFILE) FORCE
	cd libantlr3c/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libantlr3c-install_subtargets-ordered: libantlr3c/$(MAKEFILE) FORCE
	cd libantlr3c/ && $(MAKE) -f $(MAKEFILE) install
sub-libantlr3c-install_subtargets: libantlr3c/$(MAKEFILE) FORCE
	cd libantlr3c/ && $(MAKE) -f $(MAKEFILE) install
sub-libantlr3c-uninstall_subtargets-ordered: libantlr3c/$(MAKEFILE) FORCE
	cd libantlr3c/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-libantlr3c-uninstall_subtargets: libantlr3c/$(MAKEFILE) FORCE
	cd libantlr3c/ && $(MAKE) -f $(MAKEFILE) uninstall
libcparser/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libcparser/ || $(MKDIR) libcparser/ 
	cd libcparser/ && $(QMAKE) /home/chrschn/workspace/insight-vmi/libcparser/libcparser.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-libcparser-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libcparser/ || $(MKDIR) libcparser/ 
	cd libcparser/ && $(QMAKE) /home/chrschn/workspace/insight-vmi/libcparser/libcparser.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-libcparser: libcparser/$(MAKEFILE) FORCE
	cd libcparser/ && $(MAKE) -f $(MAKEFILE)
sub-libcparser-make_default-ordered: libcparser/$(MAKEFILE) sub-libantlr3c-make_default-ordered  FORCE
	cd libcparser/ && $(MAKE) -f $(MAKEFILE) 
sub-libcparser-make_default: libcparser/$(MAKEFILE) FORCE
	cd libcparser/ && $(MAKE) -f $(MAKEFILE) 
sub-libcparser-make_first-ordered: libcparser/$(MAKEFILE) sub-libantlr3c-make_first-ordered  FORCE
	cd libcparser/ && $(MAKE) -f $(MAKEFILE) first
sub-libcparser-make_first: libcparser/$(MAKEFILE) FORCE
	cd libcparser/ && $(MAKE) -f $(MAKEFILE) first
sub-libcparser-all-ordered: libcparser/$(MAKEFILE) sub-libantlr3c-all-ordered  FORCE
	cd libcparser/ && $(MAKE) -f $(MAKEFILE) all
sub-libcparser-all: libcparser/$(MAKEFILE) FORCE
	cd libcparser/ && $(MAKE) -f $(MAKEFILE) all
sub-libcparser-clean-ordered: libcparser/$(MAKEFILE) sub-libantlr3c-clean-ordered  FORCE
	cd libcparser/ && $(MAKE) -f $(MAKEFILE) clean
sub-libcparser-clean: libcparser/$(MAKEFILE) FORCE
	cd libcparser/ && $(MAKE) -f $(MAKEFILE) clean
sub-libcparser-distclean-ordered: libcparser/$(MAKEFILE) sub-libantlr3c-distclean-ordered  FORCE
	cd libcparser/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libcparser-distclean: libcparser/$(MAKEFILE) FORCE
	cd libcparser/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libcparser-install_subtargets-ordered: libcparser/$(MAKEFILE) sub-libantlr3c-install_subtargets-ordered  FORCE
	cd libcparser/ && $(MAKE) -f $(MAKEFILE) install
sub-libcparser-install_subtargets: libcparser/$(MAKEFILE) FORCE
	cd libcparser/ && $(MAKE) -f $(MAKEFILE) install
sub-libcparser-uninstall_subtargets-ordered: libcparser/$(MAKEFILE) sub-libantlr3c-uninstall_subtargets-ordered  FORCE
	cd libcparser/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-libcparser-uninstall_subtargets: libcparser/$(MAKEFILE) FORCE
	cd libcparser/ && $(MAKE) -f $(MAKEFILE) uninstall
libinsight/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libinsight/ || $(MKDIR) libinsight/ 
	cd libinsight/ && $(QMAKE) /home/chrschn/workspace/insight-vmi/libinsight/libinsight.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-libinsight-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libinsight/ || $(MKDIR) libinsight/ 
	cd libinsight/ && $(QMAKE) /home/chrschn/workspace/insight-vmi/libinsight/libinsight.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-libinsight: libinsight/$(MAKEFILE) FORCE
	cd libinsight/ && $(MAKE) -f $(MAKEFILE)
sub-libinsight-make_default-ordered: libinsight/$(MAKEFILE) sub-libcparser-make_default-ordered  FORCE
	cd libinsight/ && $(MAKE) -f $(MAKEFILE) 
sub-libinsight-make_default: libinsight/$(MAKEFILE) FORCE
	cd libinsight/ && $(MAKE) -f $(MAKEFILE) 
sub-libinsight-make_first-ordered: libinsight/$(MAKEFILE) sub-libcparser-make_first-ordered  FORCE
	cd libinsight/ && $(MAKE) -f $(MAKEFILE) first
sub-libinsight-make_first: libinsight/$(MAKEFILE) FORCE
	cd libinsight/ && $(MAKE) -f $(MAKEFILE) first
sub-libinsight-all-ordered: libinsight/$(MAKEFILE) sub-libcparser-all-ordered  FORCE
	cd libinsight/ && $(MAKE) -f $(MAKEFILE) all
sub-libinsight-all: libinsight/$(MAKEFILE) FORCE
	cd libinsight/ && $(MAKE) -f $(MAKEFILE) all
sub-libinsight-clean-ordered: libinsight/$(MAKEFILE) sub-libcparser-clean-ordered  FORCE
	cd libinsight/ && $(MAKE) -f $(MAKEFILE) clean
sub-libinsight-clean: libinsight/$(MAKEFILE) FORCE
	cd libinsight/ && $(MAKE) -f $(MAKEFILE) clean
sub-libinsight-distclean-ordered: libinsight/$(MAKEFILE) sub-libcparser-distclean-ordered  FORCE
	cd libinsight/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libinsight-distclean: libinsight/$(MAKEFILE) FORCE
	cd libinsight/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libinsight-install_subtargets-ordered: libinsight/$(MAKEFILE) sub-libcparser-install_subtargets-ordered  FORCE
	cd libinsight/ && $(MAKE) -f $(MAKEFILE) install
sub-libinsight-install_subtargets: libinsight/$(MAKEFILE) FORCE
	cd libinsight/ && $(MAKE) -f $(MAKEFILE) install
sub-libinsight-uninstall_subtargets-ordered: libinsight/$(MAKEFILE) sub-libcparser-uninstall_subtargets-ordered  FORCE
	cd libinsight/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-libinsight-uninstall_subtargets: libinsight/$(MAKEFILE) FORCE
	cd libinsight/ && $(MAKE) -f $(MAKEFILE) uninstall
insightd/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) insightd/ || $(MKDIR) insightd/ 
	cd insightd/ && $(QMAKE) /home/chrschn/workspace/insight-vmi/insightd/insightd.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-insightd-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) insightd/ || $(MKDIR) insightd/ 
	cd insightd/ && $(QMAKE) /home/chrschn/workspace/insight-vmi/insightd/insightd.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-insightd: insightd/$(MAKEFILE) FORCE
	cd insightd/ && $(MAKE) -f $(MAKEFILE)
sub-insightd-make_default-ordered: insightd/$(MAKEFILE) sub-libinsight-make_default-ordered  FORCE
	cd insightd/ && $(MAKE) -f $(MAKEFILE) 
sub-insightd-make_default: insightd/$(MAKEFILE) FORCE
	cd insightd/ && $(MAKE) -f $(MAKEFILE) 
sub-insightd-make_first-ordered: insightd/$(MAKEFILE) sub-libinsight-make_first-ordered  FORCE
	cd insightd/ && $(MAKE) -f $(MAKEFILE) first
sub-insightd-make_first: insightd/$(MAKEFILE) FORCE
	cd insightd/ && $(MAKE) -f $(MAKEFILE) first
sub-insightd-all-ordered: insightd/$(MAKEFILE) sub-libinsight-all-ordered  FORCE
	cd insightd/ && $(MAKE) -f $(MAKEFILE) all
sub-insightd-all: insightd/$(MAKEFILE) FORCE
	cd insightd/ && $(MAKE) -f $(MAKEFILE) all
sub-insightd-clean-ordered: insightd/$(MAKEFILE) sub-libinsight-clean-ordered  FORCE
	cd insightd/ && $(MAKE) -f $(MAKEFILE) clean
sub-insightd-clean: insightd/$(MAKEFILE) FORCE
	cd insightd/ && $(MAKE) -f $(MAKEFILE) clean
sub-insightd-distclean-ordered: insightd/$(MAKEFILE) sub-libinsight-distclean-ordered  FORCE
	cd insightd/ && $(MAKE) -f $(MAKEFILE) distclean
sub-insightd-distclean: insightd/$(MAKEFILE) FORCE
	cd insightd/ && $(MAKE) -f $(MAKEFILE) distclean
sub-insightd-install_subtargets-ordered: insightd/$(MAKEFILE) sub-libinsight-install_subtargets-ordered  FORCE
	cd insightd/ && $(MAKE) -f $(MAKEFILE) install
sub-insightd-install_subtargets: insightd/$(MAKEFILE) FORCE
	cd insightd/ && $(MAKE) -f $(MAKEFILE) install
sub-insightd-uninstall_subtargets-ordered: insightd/$(MAKEFILE) sub-libinsight-uninstall_subtargets-ordered  FORCE
	cd insightd/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-insightd-uninstall_subtargets: insightd/$(MAKEFILE) FORCE
	cd insightd/ && $(MAKE) -f $(MAKEFILE) uninstall
insight/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) insight/ || $(MKDIR) insight/ 
	cd insight/ && $(QMAKE) /home/chrschn/workspace/insight-vmi/insight/insight.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-insight-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) insight/ || $(MKDIR) insight/ 
	cd insight/ && $(QMAKE) /home/chrschn/workspace/insight-vmi/insight/insight.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-insight: insight/$(MAKEFILE) FORCE
	cd insight/ && $(MAKE) -f $(MAKEFILE)
sub-insight-make_default-ordered: insight/$(MAKEFILE) sub-insightd-make_default-ordered  FORCE
	cd insight/ && $(MAKE) -f $(MAKEFILE) 
sub-insight-make_default: insight/$(MAKEFILE) FORCE
	cd insight/ && $(MAKE) -f $(MAKEFILE) 
sub-insight-make_first-ordered: insight/$(MAKEFILE) sub-insightd-make_first-ordered  FORCE
	cd insight/ && $(MAKE) -f $(MAKEFILE) first
sub-insight-make_first: insight/$(MAKEFILE) FORCE
	cd insight/ && $(MAKE) -f $(MAKEFILE) first
sub-insight-all-ordered: insight/$(MAKEFILE) sub-insightd-all-ordered  FORCE
	cd insight/ && $(MAKE) -f $(MAKEFILE) all
sub-insight-all: insight/$(MAKEFILE) FORCE
	cd insight/ && $(MAKE) -f $(MAKEFILE) all
sub-insight-clean-ordered: insight/$(MAKEFILE) sub-insightd-clean-ordered  FORCE
	cd insight/ && $(MAKE) -f $(MAKEFILE) clean
sub-insight-clean: insight/$(MAKEFILE) FORCE
	cd insight/ && $(MAKE) -f $(MAKEFILE) clean
sub-insight-distclean-ordered: insight/$(MAKEFILE) sub-insightd-distclean-ordered  FORCE
	cd insight/ && $(MAKE) -f $(MAKEFILE) distclean
sub-insight-distclean: insight/$(MAKEFILE) FORCE
	cd insight/ && $(MAKE) -f $(MAKEFILE) distclean
sub-insight-install_subtargets-ordered: insight/$(MAKEFILE) sub-insightd-install_subtargets-ordered  FORCE
	cd insight/ && $(MAKE) -f $(MAKEFILE) install
sub-insight-install_subtargets: insight/$(MAKEFILE) FORCE
	cd insight/ && $(MAKE) -f $(MAKEFILE) install
sub-insight-uninstall_subtargets-ordered: insight/$(MAKEFILE) sub-insightd-uninstall_subtargets-ordered  FORCE
	cd insight/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-insight-uninstall_subtargets: insight/$(MAKEFILE) FORCE
	cd insight/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: insight-vmi.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/debug_and_release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile insight-vmi.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/debug_and_release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile insight-vmi.pro

qmake_all: sub-libantlr3c-qmake_all sub-libcparser-qmake_all sub-libinsight-qmake_all sub-insightd-qmake_all sub-insight-qmake_all FORCE

make_default: sub-libantlr3c-make_default-ordered sub-libcparser-make_default-ordered sub-libinsight-make_default-ordered sub-insightd-make_default-ordered sub-insight-make_default-ordered FORCE
make_first: sub-libantlr3c-make_first-ordered sub-libcparser-make_first-ordered sub-libinsight-make_first-ordered sub-insightd-make_first-ordered sub-insight-make_first-ordered FORCE
all: sub-libantlr3c-all-ordered sub-libcparser-all-ordered sub-libinsight-all-ordered sub-insightd-all-ordered sub-insight-all-ordered FORCE
clean: sub-libantlr3c-clean-ordered sub-libcparser-clean-ordered sub-libinsight-clean-ordered sub-insightd-clean-ordered sub-insight-clean-ordered FORCE
distclean: sub-libantlr3c-distclean-ordered sub-libcparser-distclean-ordered sub-libinsight-distclean-ordered sub-insightd-distclean-ordered sub-insight-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-libantlr3c-install_subtargets-ordered sub-libcparser-install_subtargets-ordered sub-libinsight-install_subtargets-ordered sub-insightd-install_subtargets-ordered sub-insight-install_subtargets-ordered FORCE
uninstall_subtargets: sub-libantlr3c-uninstall_subtargets-ordered sub-libcparser-uninstall_subtargets-ordered sub-libinsight-uninstall_subtargets-ordered sub-insightd-uninstall_subtargets-ordered sub-insight-uninstall_subtargets-ordered FORCE

sub-libantlr3c-sub_Debug_ordered: libantlr3c/$(MAKEFILE)
	cd libantlr3c/ && $(MAKE) debug
sub-libcparser-sub_Debug_ordered: libcparser/$(MAKEFILE) sub-libantlr3c-sub_Debug_ordered 
	cd libcparser/ && $(MAKE) debug
sub-libinsight-sub_Debug_ordered: libinsight/$(MAKEFILE) sub-libcparser-sub_Debug_ordered 
	cd libinsight/ && $(MAKE) debug
sub-insightd-sub_Debug_ordered: insightd/$(MAKEFILE) sub-libinsight-sub_Debug_ordered 
	cd insightd/ && $(MAKE) debug
sub-insight-sub_Debug_ordered: insight/$(MAKEFILE) sub-insightd-sub_Debug_ordered 
	cd insight/ && $(MAKE) debug
debug: sub-libantlr3c-sub_Debug_ordered sub-libcparser-sub_Debug_ordered sub-libinsight-sub_Debug_ordered sub-insightd-sub_Debug_ordered sub-insight-sub_Debug_ordered

sub-libantlr3c-sub_Release_ordered: libantlr3c/$(MAKEFILE)
	cd libantlr3c/ && $(MAKE) release
sub-libcparser-sub_Release_ordered: libcparser/$(MAKEFILE) sub-libantlr3c-sub_Release_ordered 
	cd libcparser/ && $(MAKE) release
sub-libinsight-sub_Release_ordered: libinsight/$(MAKEFILE) sub-libcparser-sub_Release_ordered 
	cd libinsight/ && $(MAKE) release
sub-insightd-sub_Release_ordered: insightd/$(MAKEFILE) sub-libinsight-sub_Release_ordered 
	cd insightd/ && $(MAKE) release
sub-insight-sub_Release_ordered: insight/$(MAKEFILE) sub-insightd-sub_Release_ordered 
	cd insight/ && $(MAKE) release
release: sub-libantlr3c-sub_Release_ordered sub-libcparser-sub_Release_ordered sub-libinsight-sub_Release_ordered sub-insightd-sub_Release_ordered sub-insight-sub_Release_ordered

sub-libantlr3c-check_ordered: libantlr3c/$(MAKEFILE)
	cd libantlr3c/ && $(MAKE) check
sub-libcparser-check_ordered: libcparser/$(MAKEFILE) sub-libantlr3c-check_ordered 
	cd libcparser/ && $(MAKE) check
sub-libinsight-check_ordered: libinsight/$(MAKEFILE) sub-libcparser-check_ordered 
	cd libinsight/ && $(MAKE) check
sub-insightd-check_ordered: insightd/$(MAKEFILE) sub-libinsight-check_ordered 
	cd insightd/ && $(MAKE) check
sub-insight-check_ordered: insight/$(MAKEFILE) sub-insightd-check_ordered 
	cd insight/ && $(MAKE) check
check: sub-libantlr3c-check_ordered sub-libcparser-check_ordered sub-libinsight-check_ordered sub-insightd-check_ordered sub-insight-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

